version: '3'
services:
  jenkins_server:
    image: "registry.jala.info/devops/jenkinsci/blueocean:1.4.2"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home

  gocd_server:
    image: "registry.jala.info/devops/gocd/gocd-server:v18.1.0"
    ports:
      - "8153:8153"
      - "8154:8154"
    links:
     - gocd_agent

  gocd_agent:
    image: "registry.jala.info/devops/gocd/gocd-agent-alpine-3.7:v18.1.0"
    environment:
      - GO_SERVER_URL=https://gocd_server:8154/go
    volumes:
      - ./dataGo:/dataGo
      - ./go:/home/go

  sonarqube:
    image: "registry.jala.info/devops/sonarqube:6.7.4-alpine"
    ports:
      - "9000:9000"
      - "9092:9092"
    links:
      - gocd_agent
      
